### ISSUE TITLE
Binary operator '>' cannot be applied to operands of type 'CGFloat' and 'Double'

### ISSUE THREAD

**Issue by FreakAzure** [BastiaanJansen/toast-swift#32] opened 2023-02-02 21:53 UTC
On Toast.swift, line 256 throws an error saying "Binary operator '>' cannot be applied to operands of type 'CGFloat' and 'Double'".

**Comment by Nikoloutsos** [comment] 2023-02-02 21:59
Hey @FreakAzure 👋  and thanks for reporting this. 
I could not reproduce this error. May you please share the swift version you are using?

**Comment by Nikoloutsos** [comment] 2023-03-31 10:35
@BastiaanJansen May we please close this issue?

**Closed** 2023-03-31 10:50 UTC
Labels: bug
